export const Types = {
    HOME_LOAD_DATA: 'HOME_LOAD_DATA',
    HOME_LOAD_DATA_SUCCESS: 'HOME_LOAD_DATA_SUCCESS',
    HOME_LOAD_DATA_FAIL: 'HOME_LOAD_DATA_FAIL',
    HOME_SELECTED_CITY_FINISHED_OR_CHANGED: 'HOME_SELECTED_CITY_FINISHED_OR_CHANGED',
    HOME_NAV_BAR_TRANSPARENT: 'HOME_NAV_BAR_TRANSPARENT',
    
    CITY_LIST_LOAD_DATA: 'CITY_LIST_LOAD_DATA',
    CITY_LIST_START_LOCATION: 'CITY_LIST_START_LOCATION',
    CITY_LIST_LOCATION_FINISHED: 'CITY_LIST_LOCATION_FINISHED',

    HOUSE_DETAIL_LOAD_CENTRALIZED: 'HOUSE_DETAIL_LOAD_CENTRALIZED',
    HOUSE_DETAIL_LOAD_DECENTRALIZED: 'HOUSE_DETAIL_LOAD_DECENTRALIZED',
    HOUSE_DETAIL_LOAD_DATA_FAIL: 'HOUSE_DETAIL_LOAD_DATA_FAIL'
    
    
};