export const Types = {
    HOME_LOAD_DATA: 'HOME_LOAD_DATA',
    HOME_LOAD_DATA_SUCCESS: 'HOME_LOAD_DATA_SUCCESS',
    HOME_LOAD_DATA_FAIL: 'HOME_LOAD_DATA_FAIL',
    HOME_SELECTED_CITY_FINISHED_OR_CHANGED: 'HOME_SELECTED_CITY_FINISHED_OR_CHANGED',
    HOME_LOAD_SUBWAY_DATA_FINISHED: 'HOME_LOAD_SUBWAY_DATA_FINISHED',
    HOME_SHOW_LOCATION_TIP: 'HOME_SHOW_LOCATION_TIP',
    
    CITY_LIST_LOAD_DATA: 'CITY_LIST_LOAD_DATA',
    CITY_LIST_START_LOCATION: 'CITY_LIST_START_LOCATION',
    CITY_LIST_LOCATION_FINISHED: 'CITY_LIST_LOCATION_FINISHED',

    APARTMENT_INIT: 'APARTMENT_INIT',
    APARTMENT_LOAD_DATA: 'APARTMENT_LOAD_DATA',
    APARTMENT_LOAD_DATA_FINISHED: 'APARTMENT_LOAD_DATA_FINISHED',
    APARTMENT_WILL_UNMOUNT: 'APARTMENT_WILL_UNMOUNT',

    HOUSE_DETAIL_INIT: 'HOUSE_DETAIL_INIT',
    HOUSE_DETAIL_LOAD_DATA: 'HOUSE_DETAIL_LOAD_DATA',
    HOUSE_DETAIL_LOAD_DATA_FINISHED: 'HOUSE_DETAIL_LOAD_DATA_FINISHED',
    HOUSE_DETAIL_WILL_UNMOUNT: 'HOUSE_DETAIL_WILL_UNMOUNT',

    SEARCH_HOUSE_LOAD_DATA: 'SEARCH_HOUSE_LOAD_DATA',
    SEARCH_HOUSE_LOAD_MORE_DATA: 'SEARCH_HOUSE_LOAD_MORE_DATA',
    SEARCH_HOUSE_LOAD_DATA_SUCCESS: 'SEARCH_HOUSE_LOAD_DATA_SUCCESS',
    SEARCH_HOUSE_LOAD_DATA_FAIL: 'SEARCH_HOUSE_LOAD_DATA_FAIL',
    SEARCH_HOUSE_WILL_UNMOUNT: 'SEARCH_HOUSE_WILL_UNMOUNT',

    SEARCH_HOUSE_LOAD_DATA2: 'SEARCH_HOUSE_LOAD_DATA2',
    SEARCH_HOUSE_LOAD_MORE_DATA2: 'SEARCH_HOUSE_LOAD_MORE_DATA2',
    SEARCH_HOUSE_LOAD_DATA_SUCCESS2: 'SEARCH_HOUSE_LOAD_DATA_SUCCESS2',
    SEARCH_HOUSE_LOAD_DATA_FAIL2: 'SEARCH_HOUSE_LOAD_DATA_FAIL2',
    SEARCH_HOUSE_WILL_UNMOUNT2: 'SEARCH_HOUSE_WILL_UNMOUNT2',
};